<a href="https://colab.research.google.com/github/SyedUsman07/Pytorch-deeplearning/blob/main/Pytorch_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors:**
1. Tensor os like a numpy array but more powerful for deeplearning.
2. A torch.Tensor is a multidimensional matrix containing elements of a single datatype.


In [ ]:
import torch
import numpy as np

**LISTS:**

In [ ]:
my_list = [1,2,3,4,5,6,7] #basic 1 dimentional
my_list

[1, 2, 3, 4, 5, 6, 7]

**NUMPY ARRAYS**:

In [ ]:
np1 = np.random.rand(3,5)
np1

array([[0.10662285, 0.73396249, 0.53441507, 0.25797338, 0.67896262],
       [0.37661599, 0.78504376, 0.25172966, 0.00170458, 0.75545663],
       [0.68335422, 0.97338669, 0.82005392, 0.66659953, 0.18792075]])

In [ ]:
np1.dtype

dtype('float64')

**TENSORS:**

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8848, 0.8654, 0.1389, 0.6181],
        [0.5880, 0.7620, 0.0209, 0.4894],
        [0.2811, 0.4319, 0.9976, 0.3303]])

In [ ]:
torch_3d = torch.zeros(2,3,4)
torch_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Creating tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1066, 0.7340, 0.5344, 0.2580, 0.6790],
        [0.3766, 0.7850, 0.2517, 0.0017, 0.7555],
        [0.6834, 0.9734, 0.8201, 0.6666, 0.1879]], dtype=torch.float64)

**Tensor Operations**



In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we dont know the number of items
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**VIEW and RESHAPE are very similar**

1. https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch
2. https://discuss.pytorch.org/t/whats-the-difference-between-torch-reshape-vs-torch-view/159172


In [ ]:
torch6 = torch.arange(10)
torch6


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch6[2] = 23
torch6

tensor([ 0,  1, 23,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
torch7 = torch6.reshape(2,5)
torch7

#This suggests that if you make a change in the original tensor, the daughter tensor will automatically be updated

tensor([[ 0,  1, 23,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [ ]:
# Slices
torch8 = torch.arange(10)
torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch8[7] #Its giving the scalar tensor[7] not a number keep that in mind

tensor(7)

In [ ]:
torch8[5:9]

tensor([5, 6, 7, 8])

In [ ]:
# Grab a slice
torch8 = torch8.reshape(5,2)
torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# Return column
torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])